### ISSUE TITLE
SSR Caching not working when we change the order of imports

### ISSUE THREAD

**Issue by vmayakumar** [electrode-io/electrode-react-ssr-caching#1]
When I was trying to use `electrode-react-ssr-caching` module in express application, it did not work initially. After some debugging I found that if I import `electrode-react-ssr-caching` first followed by react module imports it works but caching module does not kick in if the order is changed.

https://github.com/docs-code-examples-electrode-io/express-react-redux-webpack/blob/master/src/server.js#L2-L4

SSR CACHING WORKS:

```
import SSRCaching from "electrode-react-ssr-caching";
import React from 'react';
import ReactDOM from 'react-dom/server';
```

SSR CACHING DO NOT WORK:

```
import React from 'react';
import ReactDOM from 'react-dom/server';
import SSRCaching from "electrode-react-ssr-caching";
```

**Comment by jchip** [comment]
yes, this is expected.  caching module has to have a chance to patch react's code first.
