### ISSUE TITLE
More robust caching?

### ISSUE THREAD

**Issue by shaine** [electrode-io/electrode-react-ssr-caching#12]
Hello,

Reading through the cache implementation, it appears to be an LRU cache (right?). I see a config option to set the max age of all items in the cache, but the config is not currently used.

Are there plans to add more to the cache implementation, or a list of TODOs somewhere for it? I'm curious if there's a specific reason to roll a custom cache rather than pull in a more mature lib like lru-cache.

Thanks!

**Comment by jchip** [comment]
do you recommend one?  The cache should support limiting the physical size including the keys and the values, and automatically clean up when there are not enough space for new items.

**Comment by shaine** [comment]
I switched over to https://www.npmjs.com/package/lru-cache in a fork, I can clean that up and PR it if you'd like. I believe it meets your specification. Most importantly for me, it allows time-based invalidation of individual items in addition to having a least-recently-used size-allocation-based falloff.

**Comment by jchip** [comment]
The main reason for having a simple store was for debugging.  It was just a plain object `{}` in the beginning and that makes debugging very easy.  

Note that the cache key could be very long if it's not hashed, so a caching store should include key length when calculating max size.

I think the best way is to allow a custom cache store to be passed in, with `get` and `set`, and whatever is necessary to support these https://github.com/electrode-io/electrode-react-ssr-caching/blob/master/lib/ssr-caching.js#L351-L363.

**Comment by shaine** [comment]
I agree that that's the ideal option. My lru integration works exactly like your existing cache implementation, with hashing etc - all of the methods in lib/ssr-caching.js return the same values as they did before. I just adapted the existing features around the specific point where the cache is written or read. Since yours was already an lru cache, I think the only real difference is that the update adds the time-based cache invalidation.
