### ISSUE TITLE
Seems to fail to reassign props?

### ISSUE THREAD

**Issue by abritinthebay** [electrode-io/electrode-react-ssr-caching#14]
```
Debug: internal, implementation, error 
    TypeError: Cannot assign to read only property 'props' of object '#<Object>': Cannot assign to read only property 'props' of object '#<Object>'
    at ReactCompositeComponentWrapper.mountComponentCache ([snip]/node_modules/electrode-react-ssr-caching/lib/ssr-caching.js:294:28)
```

I get that when trying to do any caching at all - running on Node 6.9.1 and React 15.3.2

**Comment by caoyangs** [comment]
https://github.com/electrode-io/electrode-react-ssr-caching#caching

> In order for the enableCaching() method to work, you'll also need NODE_ENV set to production, or else it will throw an error.

Were you on production mode? `NODE_ENV=production`

**Comment by abritinthebay** [comment]
... I thought so. I shall double check and update.

**Comment by abritinthebay** [comment]
... ignore me. Ugh... my fault. Yes -  I was _not_ running in production mode. My bad.
