### ISSUE TITLE
Is there a plan to support react 15.4.x ?

### ISSUE THREAD

**Issue by lonelyclick** [electrode-io/electrode-react-ssr-caching#17]

**Comment by ananavati** [comment]
@lonelyclick 

`react` & `react-dom` dependencies are using [caret(^)](http://stackoverflow.com/questions/22343224/difference-between-tilde-and-caret-in-package-json) notation hence will install the latest `minor.patch` in this particular case `15.4.x`

here is the related pr to enable support for `react 15.4.x` https://github.com/electrode-io/electrode-react-ssr-caching/pull/16
