### ISSUE TITLE
Max Cache Size

### ISSUE THREAD

**Issue by withgallantry** [electrode-io/electrode-react-ssr-caching#9]
Is there any way to set a max cache size to stop it from becoming a memory leak if misconfigured?

**Comment by jchip** [comment]
The configurations are here https://github.com/electrode-io/electrode-react-ssr-caching/blob/master/lib/config.js.

There's no API for changing that, but you could do this:

``` js
const config = require("electrode-react-ssr-caching/lib/config.js");
config.MAX_CACHE_SIZE = 10*1024*1024;
```
